# Merging , Join And Concatenation

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\Users\admin\Desktop\CodeJam\Data Analytics\Python\Pandas\LOTR.csv")
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [3]:
df2 = pd.read_csv(r"C:\Users\admin\Desktop\CodeJam\Data Analytics\Python\Pandas\LOTR 2.csv")
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [4]:
df1.merge(df2) # By Default It Will Be A Inner Join

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [5]:
 df1.merge(df2, left_on='FellowshipID', right_on='FellowshipID') # Basically in sql ON e.empid = d.empid common key

   FellowshipID FirstName_x     Skills FirstName_y  Age
0          1001       Frodo     Hiding       Frodo   50
1          1002     Samwise  Gardening     Samwise   39

In [6]:
# Second Option
df1.merge(df2, how = "inner", on = "FellowshipID") # This will give same result as of the previuos one

   FellowshipID FirstName_x     Skills FirstName_y  Age
0          1001       Frodo     Hiding       Frodo   50
1          1002     Samwise  Gardening     Samwise   39

In [10]:
df1.merge(df2, how = "right", on = "FellowshipID")

   FellowshipID FirstName_x     Skills FirstName_y   Age
0          1001       Frodo     Hiding       Frodo    50
1          1002     Samwise  Gardening     Samwise    39
2          1006         NaN        NaN     Legolas  2931
3          1007         NaN        NaN      Elrond  6520
4          1008         NaN        NaN    Barromir    51

In [12]:
df1.merge(df2, how = "left", on = "FellowshipID")

   FellowshipID FirstName_x     Skills FirstName_y   Age
0          1001       Frodo     Hiding       Frodo  50.0
1          1002     Samwise  Gardening     Samwise  39.0
2          1003     Gandalf     Spells         NaN   NaN
3          1004      Pippin  Fireworks         NaN   NaN

In [13]:
df1.merge(df2, how = "outer", on = "FellowshipID")

   FellowshipID FirstName_x     Skills FirstName_y     Age
0          1001       Frodo     Hiding       Frodo    50.0
1          1002     Samwise  Gardening     Samwise    39.0
2          1003     Gandalf     Spells         NaN     NaN
3          1004      Pippin  Fireworks         NaN     NaN
4          1006         NaN        NaN     Legolas  2931.0
5          1007         NaN        NaN      Elrond  6520.0
6          1008         NaN        NaN    Barromir    51.0

In [16]:
#Join
df1.join(df2,on = "FellowshipID",  how = "outer", lsuffix="_Left", rsuffix="_Right")

,FellowshipID,FellowshipID_Left,FirstName_Left,Skills,FellowshipID_Right,FirstName_Right,Age
NaN,0,NaN,NaN,NaN,1001.0,Frodo,50.0
NaN,1,NaN,NaN,NaN,1002.0,Samwise,39.0
NaN,2,NaN,NaN,NaN,1006.0,Legolas,2931.0
NaN,3,NaN,NaN,NaN,1007.0,Elrond,6520.0
NaN,4,NaN,NaN,NaN,1008.0,Barromir,51.0
0.0,1001,1001.0,Frodo,Hiding,NaN,NaN,NaN
1.0,1002,1002.0,Samwise,Gardening,NaN,NaN,NaN
2.0,1003,1003.0,Gandalf,Spells,NaN,NaN,NaN
3.0,1004,1004.0,Pippin,Fireworks,NaN,NaN,NaN

In [21]:
df3 = df1.set_index('FellowshipID').join(df2.set_index('FellowshipID'), lsuffix="_Left", rsuffix="_Right", how = "outer")
df3 # We first created the index then join to make it clear

             FirstName_Left     Skills FirstName_Right     Age
FellowshipID
1001                  Frodo     Hiding           Frodo    50.0
1002                Samwise  Gardening         Samwise    39.0
1003                Gandalf     Spells             NaN     NaN
1004                 Pippin  Fireworks             NaN     NaN
1006                    NaN        NaN         Legolas  2931.0
1007                    NaN        NaN          Elrond  6520.0
1008                    NaN        NaN        Barromir    51.0

In [34]:
# Concatenation
pd.concat([df1,df2],join = "inner",axis = 1) # Axis 1 pr sab dikahyega and zero pr bs index o,1,2,3 column vala

   FellowshipID FirstName     Skills  FellowshipID FirstName   Age
0          1001     Frodo     Hiding          1001     Frodo    50
1          1002   Samwise  Gardening          1002   Samwise    39
2          1003   Gandalf     Spells          1006   Legolas  2931
3          1004    Pippin  Fireworks          1007    Elrond  6520