# Web Scraping Using Python

In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

In [7]:
page = requests.get(url, headers= { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' } )

soup = BeautifulSoup(page.text,"html")

# print(soup.prettify())

In [151]:
table = soup.find_all('table')[0] #As html was returning the list so we captured the table through indexing , 1st table of the page will be returned

In [153]:
world_titles = table.find_all('th') # This give the list of all the "th" tag element inside the table[1] - yha list aayi

In [141]:
world_titles_table = [title.text.strip().upper() for title in world_titles] # Here we are using the list comprehension, and iteratiing inside the list

In [142]:
world_titles_table # ['Rank', 'Name', 'Industry', 'Revenue (USD billions)', 'Employees', 'Headquarters'], 1st table col name will be returned

['RANK',
 'NAME',
 'INDUSTRY',
 'REVENUE (USD MILLIONS)',
 'REVENUE GROWTH',
 'EMPLOYEES',
 'HEADQUARTERS']

# Web Scraping Using Pandas

In [143]:
import pandas as pd

In [144]:
df = pd.DataFrame( columns = world_titles_table) # Here we created our data frame

df # Called the data frame :- 	RANK	NAME	INDUSTRY	REVENUE (USD BILLIONS)	EMPLOYEES	HEADQUARTERS

Empty DataFrame
Columns: [RANK, NAME, INDUSTRY, REVENUE (USD MILLIONS), REVENUE GROWTH, EMPLOYEES, HEADQUARTERS]
Index: []

In [145]:
# Fetching the data from the table to our dataframe
column_data = table.find_all('tr') # Yha list aayi

In [169]:
for rows in column_data[1:]: # 1 ke baad ke sare as 0th to blank list hai
    rows_data = rows.find_all('td') # Yha bhi list generate hui
    individual_row_data = [row.text.strip().upper() for row in rows_data] # List Comprehension

    length = len(df) # created a var to store different rows
    df.loc[length] = individual_row_data # Values going to the current length

In [170]:
df

,RANK,NAME,INDUSTRY,REVENUE (USD MILLIONS),REVENUE GROWTH,EMPLOYEES,HEADQUARTERS
0,1,WALMART,RETAIL,"680,985",5.1%,"2,100,000","BENTONVILLE, ARKANSAS"
1,2,AMAZON,RETAIL AND CLOUD COMPUTING,"637,959",11.0%,"1,556,000","SEATTLE, WASHINGTON"
2,3,UNITEDHEALTH GROUP,HEALTHCARE,"400,278",7.7%,"400,000","MINNETONKA, MINNESOTA"
3,4,APPLE,TECHNOLOGY,"391,035",2.0%,"164,000","CUPERTINO, CALIFORNIA"
4,5,CVS HEALTH,HEALTHCARE,"372,809",4.2%,"259,500","WOONSOCKET, RHODE ISLAND"
...,...,...,...,...,...,...,...
195,96,GENERAL DYNAMICS,AEROSPACE AND DEFENSE,"47,716",12.9%,"117,000","RESTON, VIRGINIA"
196,97,COCA-COLA,BEVERAGE,"47,061",2.9%,"69,700","ATLANTA, GEORGIA"
197,98,TIAA,FINANCIALS,"46,946",2.6%,"15,623","NEW YORK CITY, NEW YORK"
198,99,TRAVELERS,INSURANCE,"46,423",12.2%,"34,000","NEW YORK CITY, NEW YORK"
199,100,ELI LILLY,PHARMACEUTICAL,"45,043",32.0%,"47,000","INDIANAPOLIS, INDIANA"

In [171]:
df = df.drop_duplicates().reset_index(drop=True) # This removes the duplicate values from the table

In [172]:
df

,RANK,NAME,INDUSTRY,REVENUE (USD MILLIONS),REVENUE GROWTH,EMPLOYEES,HEADQUARTERS
0,1,WALMART,RETAIL,"680,985",5.1%,"2,100,000","BENTONVILLE, ARKANSAS"
1,2,AMAZON,RETAIL AND CLOUD COMPUTING,"637,959",11.0%,"1,556,000","SEATTLE, WASHINGTON"
2,3,UNITEDHEALTH GROUP,HEALTHCARE,"400,278",7.7%,"400,000","MINNETONKA, MINNESOTA"
3,4,APPLE,TECHNOLOGY,"391,035",2.0%,"164,000","CUPERTINO, CALIFORNIA"
4,5,CVS HEALTH,HEALTHCARE,"372,809",4.2%,"259,500","WOONSOCKET, RHODE ISLAND"
...,...,...,...,...,...,...,...
95,96,GENERAL DYNAMICS,AEROSPACE AND DEFENSE,"47,716",12.9%,"117,000","RESTON, VIRGINIA"
96,97,COCA-COLA,BEVERAGE,"47,061",2.9%,"69,700","ATLANTA, GEORGIA"
97,98,TIAA,FINANCIALS,"46,946",2.6%,"15,623","NEW YORK CITY, NEW YORK"
98,99,TRAVELERS,INSURANCE,"46,423",12.2%,"34,000","NEW YORK CITY, NEW YORK"
99,100,ELI LILLY,PHARMACEUTICAL,"45,043",32.0%,"47,000","INDIANAPOLIS, INDIANA"

In [173]:
# Converting the table to csv format
df.to_csv(r'C:\Users\admin\Desktop\CodeJam\Data Analytics\Python\Automated_File_Sorter_Project\Companies.csv',index = False) # remove the extra index of pandas